from _website.views.consensus_view import ConsensusView
from _website.views.events_view import EventsView
from _website.views.guildes_view import GuildesView
from _website.views.landingpage_view import LandingpageView
from _website.views.machines_view import MachinesView
from _website.views.meetings_view import MeetingsView
from _website.views.photos_view import PhotosView
from _website.views.projects_view import ProjectsView
from _website.views.spaces_view import SpacesView
from _website.views.values_view import ValuesView
from _website.views.logout_view import LogoutView
