# Generated by Django 2.2.6 on 2019-10-27 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsensusItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_name', models.CharField(blank=True, max_length=250, null=True)),
                ('text_description', models.TextField(blank=True, null=True)),
                ('boolean_meeting_1_passed', models.BooleanField(default=False)),
                ('boolean_meeting_2_passed', models.BooleanField(default=False)),
                ('int_UNIXtime_created', models.IntegerField(blank=True, null=True)),
                ('int_UNIXtime_updated', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_error_code', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('str_name', models.CharField(blank=True, max_length=250, null=True)),
                ('int_count', models.IntegerField(default=0)),
                ('text_description', models.TextField(blank=True, null=True)),
                ('text_description_no_numbers', models.TextField(blank=True, null=True)),
                ('text_context', models.TextField(blank=True, null=True)),
                ('boolean_fixed', models.BooleanField(default=False)),
                ('text_origins', models.TextField(blank=True, null=True)),
                ('text_dateUNIXtimes', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='last_updated')),
            ],
        ),
        migrations.CreateModel(
            name='Guilde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_name', models.CharField(blank=True, max_length=250, null=True)),
                ('url_featured_photo', models.URLField(blank=True, null=True)),
                ('text_description', models.TextField(blank=True, null=True)),
                ('int_UNIXtime_created', models.IntegerField(blank=True, null=True)),
                ('int_UNIXtime_updated', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_name', models.CharField(blank=True, max_length=250, null=True)),
                ('url_featured_photo', models.URLField(blank=True, null=True)),
                ('text_description', models.TextField(blank=True, null=True)),
                ('int_UNIXtime_created', models.IntegerField(blank=True, null=True)),
                ('int_UNIXtime_updated', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_name', models.CharField(blank=True, max_length=250, null=True)),
                ('url_featured_photo', models.URLField(blank=True, null=True)),
                ('text_description', models.TextField(blank=True, null=True)),
                ('int_UNIXtime_created', models.IntegerField(blank=True, null=True)),
                ('int_UNIXtime_updated', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_notes', models.TextField(blank=True, null=True)),
                ('text_keywords', models.TextField(blank=True, null=True)),
                ('int_UNIXtime_created', models.IntegerField(blank=True, null=True)),
                ('int_UNIXtime_updated', models.IntegerField(blank=True, null=True)),
                ('many_consensus_items', models.ManyToManyField(blank=True, related_name='m_consensus_items', to='hackerspace.ConsensusItem')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_name', models.CharField(blank=True, max_length=250, null=True)),
                ('int_UNIXtime_event_start', models.IntegerField(blank=True, null=True)),
                ('int_minutes_duration', models.IntegerField(default=60)),
                ('url_featured_photo', models.URLField(blank=True, null=True)),
                ('text_description', models.TextField(blank=True, null=True)),
                ('str_location_name', models.CharField(default='Noisebridge', max_length=250)),
                ('str_location_street', models.CharField(default='2169 Mission St', max_length=250)),
                ('str_location_zip', models.CharField(default='94110', max_length=10)),
                ('str_location_city', models.CharField(default='San Francisco', max_length=50)),
                ('str_location_countrycode', models.CharField(default='US', max_length=50)),
                ('str_repeating', models.CharField(choices=[('Not repeating', 'Not repeating'), ('Weekly', 'Weekly'), ('Bi-weekly', 'Bi-weekly'), ('Monthly', 'Monthly')], default='Not repeating', max_length=30)),
                ('date_repeating_end', models.DateTimeField(blank=True, null=True, verbose_name='date_repeating_end')),
                ('url_meetup_event', models.URLField(blank=True, max_length=250, null=True)),
                ('url_discuss_event', models.URLField(blank=True, max_length=250, null=True)),
                ('url_slack_event', models.URLField(blank=True, max_length=250, null=True)),
                ('int_UNIXtime_created', models.IntegerField(blank=True, null=True)),
                ('int_UNIXtime_updated', models.IntegerField(blank=True, null=True)),
                ('str_timezone', models.CharField(blank=True, default='America/Los_Angeles', max_length=100, null=True)),
                ('many_hosts', models.ManyToManyField(blank=True, related_name='m_persons', to='hackerspace.Person')),
                ('one_guilde', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='o_guilde', to='hackerspace.Guilde')),
                ('one_original_event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackerspace.Event')),
                ('one_space', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='o_space', to='hackerspace.Space')),
            ],
        ),
        migrations.AddField(
            model_name='consensusitem',
            name='one_created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='o_created_by', to='hackerspace.Person'),
        ),
    ]
