# Generated by Django 3.0 on 2019-12-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_featured_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/event_images/', verbose_name='Photo'),
        ),
    ]
