# Generated by Django 2.2.6 on 2019-10-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0002_auto_20191028_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='int_UNIXtime_event_end',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
