# Generated by Django 2.2.6 on 2019-11-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0003_event_int_unixtime_event_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingnote',
            name='text_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
