# Generated by Django 2.2.6 on 2019-11-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0004_meetingnote_text_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingnote',
            name='text_main_topics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
