# Generated by Django 3.0 on 2019-12-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0004_auto_20191210_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='boolean_looking_for_volunteers',
            field=models.BooleanField(default=False),
        ),
    ]
