# Generated by Django 3.0 on 2019-12-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0005_event_boolean_looking_for_volunteers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consensus',
            old_name='text_description',
            new_name='text_description_en_US',
        ),
        migrations.RenameField(
            model_name='error',
            old_name='text_description',
            new_name='text_description_en_US',
        ),
        migrations.RenameField(
            model_name='guilde',
            old_name='text_description',
            new_name='text_description_en_US',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='text_description',
            new_name='text_description_en_US',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='text_description',
            new_name='text_description_en_US',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='text_description',
            new_name='text_description_en_US',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='text_description',
            new_name='text_description_en_US',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='text_description',
            new_name='text_description_en_US',
        ),
        migrations.RenameField(
            model_name='wish',
            old_name='text_description',
            new_name='text_description_en_US',
        ),
        migrations.RemoveField(
            model_name='event',
            name='text_description',
        ),
        migrations.AddField(
            model_name='event',
            name='text_description_en_US',
            field=models.TextField(blank=True, null=True, verbose_name='Description en-US'),
        ),
        migrations.AddField(
            model_name='event',
            name='text_description_he_IL',
            field=models.TextField(blank=True, null=True, verbose_name='Description he-IL'),
        ),
    ]
