# Generated by Django 3.0 on 2019-12-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0006_auto_20191211_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consensus',
            old_name='str_name',
            new_name='str_name_en_US',
        ),
        migrations.RenameField(
            model_name='error',
            old_name='str_name',
            new_name='str_name_en_US',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='str_name',
            new_name='str_name_en_US',
        ),
        migrations.RenameField(
            model_name='guilde',
            old_name='str_name',
            new_name='str_name_en_US',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='str_name',
            new_name='str_name_en_US',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='str_name',
            new_name='str_name_en_US',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='str_name',
            new_name='str_name_en_US',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='str_name',
            new_name='str_name_en_US',
        ),
        migrations.RenameField(
            model_name='wish',
            old_name='str_name',
            new_name='str_name_en_US',
        ),
    ]
