# Generated by Django 2.2.6 on 2019-11-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0006_guilde_many_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='guilde',
            name='str_slug',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
