# Generated by Django 3.0 on 2019-12-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0008_auto_20191211_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='text_description_he_IL',
            field=models.TextField(blank=True, null=True, verbose_name='Description he-IL'),
        ),
        migrations.AlterField(
            model_name='space',
            name='text_description_en_US',
            field=models.TextField(blank=True, null=True, verbose_name='Description en-US'),
        ),
    ]
