# Generated by Django 2.2.6 on 2019-11-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0008_space_str_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_slug', models.CharField(blank=True, max_length=250, null=True)),
                ('str_name', models.CharField(blank=True, max_length=250, null=True)),
                ('url_featured_photo', models.URLField(blank=True, null=True)),
                ('text_description', models.TextField(blank=True, null=True)),
                ('int_UNIXtime_created', models.IntegerField(blank=True, null=True)),
                ('int_UNIXtime_updated', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
