# Generated by Django 3.0 on 2019-12-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0009_auto_20191211_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='consensus',
            name='str_name_he_IL',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name he-IL'),
        ),
        migrations.AddField(
            model_name='event',
            name='str_name_he_IL',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name he-IL'),
        ),
        migrations.AddField(
            model_name='guilde',
            name='str_name_he_IL',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name he-IL'),
        ),
        migrations.AddField(
            model_name='machine',
            name='str_name_he_IL',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name he-IL'),
        ),
        migrations.AddField(
            model_name='person',
            name='str_name_he_IL',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name he-IL'),
        ),
        migrations.AddField(
            model_name='project',
            name='str_name_he_IL',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name he-IL'),
        ),
        migrations.AddField(
            model_name='space',
            name='str_name_he_IL',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name he-IL'),
        ),
        migrations.AddField(
            model_name='wish',
            name='str_name_he_IL',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name he-IL'),
        ),
        migrations.AlterField(
            model_name='consensus',
            name='str_name_en_US',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name en-US'),
        ),
        migrations.AlterField(
            model_name='event',
            name='str_name_en_US',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name en-US'),
        ),
        migrations.AlterField(
            model_name='guilde',
            name='str_name_en_US',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name en-US'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='str_name_en_US',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name en-US'),
        ),
        migrations.AlterField(
            model_name='person',
            name='str_name_en_US',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name en-US'),
        ),
        migrations.AlterField(
            model_name='project',
            name='str_name_en_US',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name en-US'),
        ),
        migrations.AlterField(
            model_name='space',
            name='str_name_en_US',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name en-US'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='str_name_en_US',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name en-US'),
        ),
    ]
