# Generated by Django 2.2.6 on 2019-11-09 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0009_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='one_guilde',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='o_machine_guilde', to='hackerspace.Guilde'),
        ),
        migrations.AddField(
            model_name='machine',
            name='one_space',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='o_machine_space', to='hackerspace.Space'),
        ),
    ]
