# Generated by Django 3.0 on 2019-12-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0010_auto_20191211_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='str_description_auto_translated_from',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='str_name_auto_translated_from',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
