# Generated by Django 3.0 on 2019-12-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0011_auto_20191211_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='str_description_auto_translated_from',
        ),
        migrations.RemoveField(
            model_name='event',
            name='str_name_auto_translated_from',
        ),
        migrations.RemoveField(
            model_name='event',
            name='url_discourse_wish',
        ),
    ]
