# Generated by Django 2.2.6 on 2019-11-10 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0011_auto_20191110_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='one_guilde',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='o_spaces_guilde', to='hackerspace.Guilde'),
        ),
    ]
