# Generated by Django 3.0 on 2019-12-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0012_auto_20191214_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='float_lat',
            field=models.FloatField(blank=True, default=37.762389, null=True, verbose_name='Lat'),
        ),
        migrations.AlterField(
            model_name='event',
            name='float_lon',
            field=models.FloatField(blank=True, default=-122.4191587, null=True, verbose_name='Lon'),
        ),
        migrations.AlterField(
            model_name='event',
            name='str_location',
            field=models.CharField(default='Noisebridge<br>2169 Mission St<br94110, San Francisco, CA, US', max_length=250, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='str_timezone',
            field=models.CharField(blank=True, default='America/Los_Angeles', max_length=100, null=True, verbose_name='Timezone'),
        ),
    ]
