# Generated by Django 3.0 on 2019-12-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0013_auto_20191215_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='float_lat',
            field=models.FloatField(blank=True, default=32.0523183, null=True, verbose_name='Lat'),
        ),
        migrations.AlterField(
            model_name='event',
            name='float_lon',
            field=models.FloatField(blank=True, default=34.7678285, null=True, verbose_name='Lon'),
        ),
        migrations.AlterField(
            model_name='event',
            name='str_location',
            field=models.CharField(default='TAMI<br>Kibbutz Galuyot 45<br6655031, Tel Aviv, Tel Aviv-Yafo, IL', max_length=250, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='str_timezone',
            field=models.CharField(blank=True, default='Asia/Jerusalem', max_length=100, null=True, verbose_name='Timezone'),
        ),
    ]
