# Generated by Django 2.2.6 on 2019-11-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0014_auto_20191110_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='url_wiki',
        ),
        migrations.AddField(
            model_name='person',
            name='url_discourse',
            field=models.URLField(blank=True, null=True, verbose_name='Discourse URL'),
        ),
    ]
