# Generated by Django 3.0 on 2019-12-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0014_auto_20191215_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='image_featured_photo',
            field=models.ImageField(blank=True, null=True, upload_to='spaces_images', verbose_name='Photo'),
        ),
    ]
