# Generated by Django 2.2.6 on 2019-11-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0015_auto_20191110_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('url_featured_photo', models.URLField(blank=True, null=True, verbose_name='Photo URL')),
                ('url_discourse', models.URLField(blank=True, null=True, verbose_name='Discourse URL')),
                ('text_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('int_UNIXtime_created', models.IntegerField(blank=True, null=True)),
                ('int_UNIXtime_updated', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
