# Generated by Django 2.2.6 on 2019-11-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0016_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='str_slug',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
