# Generated by Django 2.2.6 on 2019-11-11 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0017_project_str_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='one_creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='o_project_creator', to='hackerspace.Person', verbose_name='Creator'),
        ),
        migrations.CreateModel(
            name='Consensus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('text_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('str_status', models.CharField(blank=True, choices=[('new', 'New'), ('passed_1', 'Meeting 1 passed'), ('approved', 'Meeting 2 passed => Approved')], max_length=250, null=True, verbose_name='Status')),
                ('int_UNIXtime_created', models.IntegerField(blank=True, null=True)),
                ('int_UNIXtime_updated', models.IntegerField(blank=True, null=True)),
                ('one_creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='o_consensus_creator', to='hackerspace.Person', verbose_name='Creator')),
            ],
        ),
    ]
