# Generated by Django 2.2.6 on 2019-11-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0018_auto_20191111_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='consensus',
            name='url_discourse',
            field=models.URLField(blank=True, null=True, verbose_name='Discourse URL'),
        ),
        migrations.AlterField(
            model_name='consensus',
            name='str_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('passed_1', 'Meeting 1 passed'), ('approved', 'Approved')], max_length=250, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='meetingnote',
            name='many_consensus_items',
            field=models.ManyToManyField(blank=True, related_name='m_consensus_items', to='hackerspace.Consensus'),
        ),
        migrations.DeleteModel(
            name='ConsensusItem',
        ),
    ]
