# Generated by Django 2.2.6 on 2019-11-11 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0019_auto_20191111_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('text_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('url_discourse', models.URLField(blank=True, null=True, verbose_name='Discourse URL')),
                ('int_UNIXtime_created', models.IntegerField(blank=True, null=True)),
                ('int_UNIXtime_updated', models.IntegerField(blank=True, null=True)),
                ('one_person', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='o_wishes_person', to='hackerspace.Person', verbose_name='Guilde')),
            ],
        ),
    ]
