# Generated by Django 2.2.6 on 2019-11-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0020_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consensus',
            name='str_status',
            field=models.CharField(choices=[('new', 'New'), ('passed_1', 'Meeting 1 passed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='new', max_length=250, verbose_name='Status'),
        ),
    ]
