# Generated by Django 2.2.6 on 2019-11-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0022_event_str_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url_discourse_wish',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='discourse wish URL'),
        ),
    ]
