# Generated by Django 2.2.6 on 2019-11-18 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0023_event_url_discourse_wish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='str_slug',
        ),
    ]
