# Generated by Django 2.2.6 on 2019-11-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0024_remove_project_str_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='boolean_auto_approve',
            field=models.BooleanField(default=True),
        ),
    ]
