# Generated by Django 2.2.6 on 2019-11-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0025_event_boolean_auto_approve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='boolean_auto_approve',
            new_name='boolean_approved',
        ),
    ]
