# Generated by Django 2.2.6 on 2019-11-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0026_auto_20191124_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='str_location_city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='str_location_countrycode',
        ),
        migrations.RemoveField(
            model_name='event',
            name='str_location_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='str_location_street',
        ),
        migrations.RemoveField(
            model_name='event',
            name='str_location_zip',
        ),
        migrations.AddField(
            model_name='event',
            name='str_location',
            field=models.CharField(default={'CITY': 'San Francisco', 'COUNTRYCODE': 'US', 'EXTRA_INFO': '(entrence left next to the supermarket)', 'STATE': 'CA', 'STREET': '2169 Mission St', 'ZIP': '94110'}, max_length=250, verbose_name='Location'),
        ),
    ]
