# Generated by Django 2.2.6 on 2019-11-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0028_auto_20191124_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='str_crowd_size',
            field=models.CharField(choices=[('small', 'Up to 10 people'), ('medium', 'Up to 20 people'), ('large', 'More than 20 people')], default='small', max_length=250, verbose_name='Expected crowd size'),
        ),
        migrations.AddField(
            model_name='event',
            name='str_welcomer',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='(for large events) Who welcomes people at the door?'),
        ),
    ]
