# Generated by Django 2.2.6 on 2019-11-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0031_auto_20191127_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='float_lat',
            field=models.FloatField(blank=True, default=37.762389, null=True, verbose_name='Lat'),
        ),
        migrations.AlterField(
            model_name='event',
            name='float_lon',
            field=models.FloatField(blank=True, default=-122.4191587, null=True, verbose_name='Lon'),
        ),
    ]
