# Generated by Django 2.2.6 on 2019-11-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0033_auto_20191128_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='many_hosts',
            field=models.ManyToManyField(blank=True, related_name='m_persons', to='hackerspace.Person', verbose_name='Hosts'),
        ),
    ]
