# Generated by Django 2.2.6 on 2019-11-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0034_auto_20191128_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='str_slug',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
