# Generated by Django 2.2.6 on 2019-11-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0035_auto_20191128_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='url_slack_event',
        ),
    ]
