# Generated by Django 2.2.6 on 2019-12-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0036_remove_event_url_slack_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('url_image', models.URLField(blank=True, max_length=250, null=True, verbose_name='Image URL')),
                ('str_source', models.CharField(blank=True, max_length=250, null=True, verbose_name='Source')),
                ('int_UNIXtime_created', models.IntegerField(blank=True, null=True)),
                ('int_UNIXtime_updated', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
