# Generated by Django 2.2.6 on 2019-12-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0037_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url_post',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Post URL'),
        ),
    ]
